// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/agent.proto

package kernelharborpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HostName  string                 `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	EventType string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventId   string                 `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ProcessId uint32                 `protobuf:"varint,5,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Comm      string                 `protobuf:"bytes,6,opt,name=comm,proto3" json:"comm,omitempty"`
	// execve fields
	ImagePath   string `protobuf:"bytes,7,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	CommandLine string `protobuf:"bytes,8,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	// open fields
	FilePath string `protobuf:"bytes,9,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Flags    int32  `protobuf:"varint,10,opt,name=flags,proto3" json:"flags,omitempty"`
	Mode     uint32 `protobuf:"varint,11,opt,name=mode,proto3" json:"mode,omitempty"`
	// connect fields
	RemoteAddr string `protobuf:"bytes,12,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	RemotePort uint32 `protobuf:"varint,13,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	LocalAddr  string `protobuf:"bytes,14,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	LocalPort  uint32 `protobuf:"varint,15,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	// process ancestry
	ProcessGuid string `protobuf:"bytes,16,opt,name=process_guid,json=processGuid,proto3" json:"process_guid,omitempty"`
	ParentGuid  string `protobuf:"bytes,17,opt,name=parent_guid,json=parentGuid,proto3" json:"parent_guid,omitempty"`
	ParentPid   uint32 `protobuf:"varint,18,opt,name=parent_pid,json=parentPid,proto3" json:"parent_pid,omitempty"`
	// decoded open flags
	FlagsDesc     string `protobuf:"bytes,19,opt,name=flags_desc,json=flagsDesc,proto3" json:"flags_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Event) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetProcessId() uint32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *Event) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *Event) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *Event) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *Event) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Event) GetFlags() int32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Event) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Event) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *Event) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *Event) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *Event) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *Event) GetProcessGuid() string {
	if x != nil {
		return x.ProcessGuid
	}
	return ""
}

func (x *Event) GetParentGuid() string {
	if x != nil {
		return x.ParentGuid
	}
	return ""
}

func (x *Event) GetParentPid() uint32 {
	if x != nil {
		return x.ParentPid
	}
	return 0
}

func (x *Event) GetFlagsDesc() string {
	if x != nil {
		return x.FlagsDesc
	}
	return ""
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *IngestRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint32                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Actions       []*Action              `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type AnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AnalysisRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *AnalysisRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type AnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Evidence      []string               `protobuf:"bytes,4,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AnalysisResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *AnalysisResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalysisResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalysisResponse) GetEvidence() []string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ActionType    string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Action) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *Action) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Action) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ActionRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ActionResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\fkernelharbor\"\xba\x04\n" +
	"\x05Event\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"process_id\x18\x05 \x01(\rR\tprocessId\x12\x12\n" +
	"\x04comm\x18\x06 \x01(\tR\x04comm\x12\x1d\n" +
	"\n" +
	"image_path\x18\a \x01(\tR\timagePath\x12!\n" +
	"\fcommand_line\x18\b \x01(\tR\vcommandLine\x12\x1b\n" +
	"\tfile_path\x18\t \x01(\tR\bfilePath\x12\x14\n" +
	"\x05flags\x18\n" +
	" \x01(\x05R\x05flags\x12\x12\n" +
	"\x04mode\x18\v \x01(\rR\x04mode\x12\x1f\n" +
	"\vremote_addr\x18\f \x01(\tR\n" +
	"remoteAddr\x12\x1f\n" +
	"\vremote_port\x18\r \x01(\rR\n" +
	"remotePort\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x0e \x01(\tR\tlocalAddr\x12\x1d\n" +
	"\n" +
	"local_port\x18\x0f \x01(\rR\tlocalPort\x12!\n" +
	"\fprocess_guid\x18\x10 \x01(\tR\vprocessGuid\x12\x1f\n" +
	"\vparent_guid\x18\x11 \x01(\tR\n" +
	"parentGuid\x12\x1d\n" +
	"\n" +
	"parent_pid\x18\x12 \x01(\rR\tparentPid\x12\x1d\n" +
	"\n" +
	"flags_desc\x18\x13 \x01(\tR\tflagsDesc\"<\n" +
	"\rIngestRequest\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.kernelharbor.EventR\x06events\"\\\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\rR\baccepted\x12.\n" +
	"\aactions\x18\x02 \x03(\v2\x14.kernelharbor.ActionR\aactions\"D\n" +
	"\x0fAnalysisRequest\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"\x82\x01\n" +
	"\x10AnalysisResponse\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1a\n" +
	"\bevidence\x18\x04 \x03(\tR\bevidence\"i\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\",\n" +
	"\rActionRequest\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\"@\n" +
	"\x0eActionResponse\x12.\n" +
	"\aactions\x18\x01 \x03(\v2\x14.kernelharbor.ActionR\aactions2\xe8\x01\n" +
	"\fAgentService\x12C\n" +
	"\x06Ingest\x12\x1b.kernelharbor.IngestRequest\x1a\x1c.kernelharbor.IngestResponse\x12H\n" +
	"\aAnalyze\x12\x1d.kernelharbor.AnalysisRequest\x1a\x1e.kernelharbor.AnalysisResponse\x12I\n" +
	"\fFetchActions\x12\x1b.kernelharbor.ActionRequest\x1a\x1c.kernelharbor.ActionResponseB#Z!kernelharbor/proto/kernelharborpbb\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_agent_proto_goTypes = []any{
	(*Event)(nil),            // 0: kernelharbor.Event
	(*IngestRequest)(nil),    // 1: kernelharbor.IngestRequest
	(*IngestResponse)(nil),   // 2: kernelharbor.IngestResponse
	(*AnalysisRequest)(nil),  // 3: kernelharbor.AnalysisRequest
	(*AnalysisResponse)(nil), // 4: kernelharbor.AnalysisResponse
	(*Action)(nil),           // 5: kernelharbor.Action
	(*ActionRequest)(nil),    // 6: kernelharbor.ActionRequest
	(*ActionResponse)(nil),   // 7: kernelharbor.ActionResponse
}
var file_proto_agent_proto_depIdxs = []int32{
	0, // 0: kernelharbor.IngestRequest.events:type_name -> kernelharbor.Event
	5, // 1: kernelharbor.IngestResponse.actions:type_name -> kernelharbor.Action
	5, // 2: kernelharbor.ActionResponse.actions:type_name -> kernelharbor.Action
	1, // 3: kernelharbor.AgentService.Ingest:input_type -> kernelharbor.IngestRequest
	3, // 4: kernelharbor.AgentService.Analyze:input_type -> kernelharbor.AnalysisRequest
	6, // 5: kernelharbor.AgentService.FetchActions:input_type -> kernelharbor.ActionRequest
	2, // 6: kernelharbor.AgentService.Ingest:output_type -> kernelharbor.IngestResponse
	4, // 7: kernelharbor.AgentService.Analyze:output_type -> kernelharbor.AnalysisResponse
	7, // 8: kernelharbor.AgentService.FetchActions:output_type -> kernelharbor.ActionResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
