// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadOpenTracer returns the embedded CollectionSpec for openTracer.
func loadOpenTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OpenTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load openTracer: %w", err)
	}

	return spec, err
}

// loadOpenTracerObjects loads openTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*openTracerObjects
//	*openTracerPrograms
//	*openTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOpenTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOpenTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// openTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openTracerSpecs struct {
	openTracerProgramSpecs
	openTracerMapSpecs
	openTracerVariableSpecs
}

// openTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openTracerProgramSpecs struct {
	HandleOpen *ebpf.ProgramSpec `ebpf:"handle_open"`
}

// openTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openTracerMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// openTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openTracerVariableSpecs struct {
}

// openTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOpenTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type openTracerObjects struct {
	openTracerPrograms
	openTracerMaps
	openTracerVariables
}

func (o *openTracerObjects) Close() error {
	return _OpenTracerClose(
		&o.openTracerPrograms,
		&o.openTracerMaps,
	)
}

// openTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOpenTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type openTracerMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *openTracerMaps) Close() error {
	return _OpenTracerClose(
		m.Events,
	)
}

// openTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOpenTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type openTracerVariables struct {
}

// openTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOpenTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type openTracerPrograms struct {
	HandleOpen *ebpf.Program `ebpf:"handle_open"`
}

func (p *openTracerPrograms) Close() error {
	return _OpenTracerClose(
		p.HandleOpen,
	)
}

func _OpenTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed opentracer_bpfel.o
var _OpenTracerBytes []byte
