// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadConnectTracer returns the embedded CollectionSpec for connectTracer.
func loadConnectTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnectTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load connectTracer: %w", err)
	}

	return spec, err
}

// loadConnectTracerObjects loads connectTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*connectTracerObjects
//	*connectTracerPrograms
//	*connectTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConnectTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConnectTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// connectTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectTracerSpecs struct {
	connectTracerProgramSpecs
	connectTracerMapSpecs
	connectTracerVariableSpecs
}

// connectTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectTracerProgramSpecs struct {
	HandleConnect *ebpf.ProgramSpec `ebpf:"handle_connect"`
}

// connectTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectTracerMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// connectTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectTracerVariableSpecs struct {
}

// connectTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConnectTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectTracerObjects struct {
	connectTracerPrograms
	connectTracerMaps
	connectTracerVariables
}

func (o *connectTracerObjects) Close() error {
	return _ConnectTracerClose(
		&o.connectTracerPrograms,
		&o.connectTracerMaps,
	)
}

// connectTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConnectTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectTracerMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *connectTracerMaps) Close() error {
	return _ConnectTracerClose(
		m.Events,
	)
}

// connectTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConnectTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectTracerVariables struct {
}

// connectTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConnectTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectTracerPrograms struct {
	HandleConnect *ebpf.Program `ebpf:"handle_connect"`
}

func (p *connectTracerPrograms) Close() error {
	return _ConnectTracerClose(
		p.HandleConnect,
	)
}

func _ConnectTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connecttracer_bpfel.o
var _ConnectTracerBytes []byte
