// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadExecveTracer returns the embedded CollectionSpec for execveTracer.
func loadExecveTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecveTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load execveTracer: %w", err)
	}

	return spec, err
}

// loadExecveTracerObjects loads execveTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*execveTracerObjects
//	*execveTracerPrograms
//	*execveTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExecveTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExecveTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// execveTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveTracerSpecs struct {
	execveTracerProgramSpecs
	execveTracerMapSpecs
	execveTracerVariableSpecs
}

// execveTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveTracerProgramSpecs struct {
	HandleExec *ebpf.ProgramSpec `ebpf:"handle_exec"`
}

// execveTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveTracerMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// execveTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveTracerVariableSpecs struct {
}

// execveTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExecveTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type execveTracerObjects struct {
	execveTracerPrograms
	execveTracerMaps
	execveTracerVariables
}

func (o *execveTracerObjects) Close() error {
	return _ExecveTracerClose(
		&o.execveTracerPrograms,
		&o.execveTracerMaps,
	)
}

// execveTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExecveTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type execveTracerMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *execveTracerMaps) Close() error {
	return _ExecveTracerClose(
		m.Events,
	)
}

// execveTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExecveTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type execveTracerVariables struct {
}

// execveTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExecveTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type execveTracerPrograms struct {
	HandleExec *ebpf.Program `ebpf:"handle_exec"`
}

func (p *execveTracerPrograms) Close() error {
	return _ExecveTracerClose(
		p.HandleExec,
	)
}

func _ExecveTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execvetracer_bpfeb.o
var _ExecveTracerBytes []byte
