// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type openatTracerPathScratch struct {
	_      structs.HostLayout
	Names  [20][48]int8
	Lens   [20]int32
	Count  int32
	Output [256]int8
}

// loadOpenatTracer returns the embedded CollectionSpec for openatTracer.
func loadOpenatTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OpenatTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load openatTracer: %w", err)
	}

	return spec, err
}

// loadOpenatTracerObjects loads openatTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*openatTracerObjects
//	*openatTracerPrograms
//	*openatTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOpenatTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOpenatTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// openatTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openatTracerSpecs struct {
	openatTracerProgramSpecs
	openatTracerMapSpecs
	openatTracerVariableSpecs
}

// openatTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openatTracerProgramSpecs struct {
	HandleOpenat *ebpf.ProgramSpec `ebpf:"handle_openat"`
}

// openatTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openatTracerMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	PathScratch *ebpf.MapSpec `ebpf:"path_scratch"`
}

// openatTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openatTracerVariableSpecs struct {
}

// openatTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOpenatTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type openatTracerObjects struct {
	openatTracerPrograms
	openatTracerMaps
	openatTracerVariables
}

func (o *openatTracerObjects) Close() error {
	return _OpenatTracerClose(
		&o.openatTracerPrograms,
		&o.openatTracerMaps,
	)
}

// openatTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOpenatTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type openatTracerMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	PathScratch *ebpf.Map `ebpf:"path_scratch"`
}

func (m *openatTracerMaps) Close() error {
	return _OpenatTracerClose(
		m.Events,
		m.PathScratch,
	)
}

// openatTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOpenatTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type openatTracerVariables struct {
}

// openatTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOpenatTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type openatTracerPrograms struct {
	HandleOpenat *ebpf.Program `ebpf:"handle_openat"`
}

func (p *openatTracerPrograms) Close() error {
	return _OpenatTracerClose(
		p.HandleOpenat,
	)
}

func _OpenatTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed openattracer_bpfel.o
var _OpenatTracerBytes []byte
