// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdpBlocklistLpmKeyV4 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [4]uint8
}

type xdpBlocklistLpmKeyV6 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [16]uint8
}

// loadXdpBlocklist returns the embedded CollectionSpec for xdpBlocklist.
func loadXdpBlocklist() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpBlocklistBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdpBlocklist: %w", err)
	}

	return spec, err
}

// loadXdpBlocklistObjects loads xdpBlocklist and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpBlocklistObjects
//	*xdpBlocklistPrograms
//	*xdpBlocklistMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpBlocklistObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdpBlocklist()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpBlocklistSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpBlocklistSpecs struct {
	xdpBlocklistProgramSpecs
	xdpBlocklistMapSpecs
	xdpBlocklistVariableSpecs
}

// xdpBlocklistProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpBlocklistProgramSpecs struct {
	XdpBlocklist *ebpf.ProgramSpec `ebpf:"xdp_blocklist"`
}

// xdpBlocklistMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpBlocklistMapSpecs struct {
	BlocklistV4 *ebpf.MapSpec `ebpf:"blocklist_v4"`
	BlocklistV6 *ebpf.MapSpec `ebpf:"blocklist_v6"`
}

// xdpBlocklistVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpBlocklistVariableSpecs struct {
}

// xdpBlocklistObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpBlocklistObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpBlocklistObjects struct {
	xdpBlocklistPrograms
	xdpBlocklistMaps
	xdpBlocklistVariables
}

func (o *xdpBlocklistObjects) Close() error {
	return _XdpBlocklistClose(
		&o.xdpBlocklistPrograms,
		&o.xdpBlocklistMaps,
	)
}

// xdpBlocklistMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpBlocklistObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpBlocklistMaps struct {
	BlocklistV4 *ebpf.Map `ebpf:"blocklist_v4"`
	BlocklistV6 *ebpf.Map `ebpf:"blocklist_v6"`
}

func (m *xdpBlocklistMaps) Close() error {
	return _XdpBlocklistClose(
		m.BlocklistV4,
		m.BlocklistV6,
	)
}

// xdpBlocklistVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpBlocklistObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpBlocklistVariables struct {
}

// xdpBlocklistPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpBlocklistObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpBlocklistPrograms struct {
	XdpBlocklist *ebpf.Program `ebpf:"xdp_blocklist"`
}

func (p *xdpBlocklistPrograms) Close() error {
	return _XdpBlocklistClose(
		p.XdpBlocklist,
	)
}

func _XdpBlocklistClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpblocklist_bpfel.o
var _XdpBlocklistBytes []byte
